specialist_mapping = {
    # General / Common
    "fever": "General Physician",
    "fatigue": "General Physician",
    "weakness": "General Physician",
    "night sweats": "General Physician",
    "chills": "General Physician",
    "loss of appetite": "Gastroenterologist",
    "unexplained weight loss": "General Physician",
    "unexplained weight gain": "Endocrinologist",

    # Heart / Chest
    "chest pain": "Cardiologist",
    "palpitations": "Cardiologist",
    "shortness of breath": "Cardiologist",
    "high blood pressure": "Cardiologist",
    "low blood pressure": "Cardiologist",
    "high cholesterol": "Cardiologist",
    "heart murmur": "Cardiologist",
    "swollen ankles": "Cardiologist",
    "irregular heartbeat": "Cardiologist",

    # Respiratory
    "asthma": "Pulmonologist",
    "chronic cough": "Pulmonologist",
    "dry cough": "Pulmonologist",
    "productive cough": "Pulmonologist",
    "wheezing": "Pulmonologist",
    "sleep apnea": "Pulmonologist",
    "snoring": "Pulmonologist",
    "pneumonia": "Pulmonologist",
    "tuberculosis": "Pulmonologist",
    "bronchitis": "Pulmonologist",

    # Digestive
    "abdominal pain": "Gastroenterologist",
    "upper abdominal pain": "Gastroenterologist",
    "lower abdominal pain": "Gastroenterologist",
    "nausea": "Gastroenterologist",
    "vomiting": "Gastroenterologist",
    "diarrhea": "Gastroenterologist",
    "constipation": "Gastroenterologist",
    "bloating": "Gastroenterologist",
    "indigestion": "Gastroenterologist",
    "acid reflux": "Gastroenterologist",
    "heartburn": "Gastroenterologist",
    "peptic ulcer": "Gastroenterologist",
    "blood in stool": "Gastroenterologist",
    "black stool": "Gastroenterologist",
    "liver disease": "Hepatologist",
    "jaundice": "Hepatologist",
    "gallstones": "Gastroenterologist",
    "pancreatitis": "Gastroenterologist",
    "irritable bowel syndrome": "Gastroenterologist",
    "crohn's disease": "Gastroenterologist",
    "ulcerative colitis": "Gastroenterologist",

    # Endocrine / Hormonal
    "diabetes": "Endocrinologist",
    "thyroid problem": "Endocrinologist",
    "goiter": "Endocrinologist",
    "hyperthyroidism": "Endocrinologist",
    "hypothyroidism": "Endocrinologist",
    "infertility": "Endocrinologist",
    "low testosterone": "Endocrinologist",
    "hormonal imbalance": "Endocrinologist",
    "cushing syndrome": "Endocrinologist",
    "adrenal problem": "Endocrinologist",

    # Skin / Hair / Nails
    "skin rash": "Dermatologist",
    "acne": "Dermatologist",
    "eczema": "Dermatologist",
    "psoriasis": "Dermatologist",
    "urticaria": "Allergist",
    "itchy skin": "Dermatologist",
    "hair loss": "Dermatologist",
    "dandruff": "Dermatologist",
    "alopecia": "Dermatologist",
    "skin infection": "Dermatologist",
    "fungal infection": "Dermatologist",
    "nail fungus": "Dermatologist",
    "skin cancer": "Oncologist",
    "moles": "Dermatologist",
    "vitiligo": "Dermatologist",
    "warts": "Dermatologist",

    # Bones / Joints / Muscles
    "joint pain": "Orthopedic Surgeon",
    "back pain": "Orthopedic Surgeon",
    "neck pain": "Orthopedic Surgeon",
    "shoulder pain": "Orthopedic Surgeon",
    "knee pain": "Orthopedic Surgeon",
    "hip pain": "Orthopedic Surgeon",
    "fracture": "Orthopedic Surgeon",
    "dislocation": "Orthopedic Surgeon",
    "sprain": "Orthopedic Surgeon",
    "strain": "Orthopedic Surgeon",
    "arthritis": "Rheumatologist",
    "rheumatoid arthritis": "Rheumatologist",
    "gout": "Rheumatologist",
    "osteoporosis": "Orthopedic Surgeon",
    "scoliosis": "Orthopedic Surgeon",
    "sports injury": "Sports Medicine Specialist",

    # Brain / Nerves
    "headache": "Neurologist",
    "migraine": "Neurologist",
    "seizures": "Neurologist",
    "epilepsy": "Neurologist",
    "stroke": "Neurologist",
    "parkinson's disease": "Neurologist",
    "multiple sclerosis": "Neurologist",
    "tremors": "Neurologist",
    "paralysis": "Neurologist",
    "memory loss": "Neurologist",
    "confusion": "Neurologist",
    "dementia": "Neurologist",
    "brain tumor": "Neurosurgeon",
    "vertigo": "Neurologist",

    # Mental Health
    "depression": "Psychiatrist",
    "anxiety": "Psychiatrist",
    "panic attack": "Psychiatrist",
    "stress": "Psychologist",
    "insomnia": "Psychiatrist",
    "schizophrenia": "Psychiatrist",
    "bipolar disorder": "Psychiatrist",
    "adhd": "Psychiatrist",
    "autism": "Psychiatrist",
    "phobia": "Psychologist",
    "ocd": "Psychiatrist",

    # ENT
    "ear pain": "ENT Specialist",
    "ear discharge": "ENT Specialist",
    "hearing loss": "ENT Specialist",
    "tinnitus": "ENT Specialist",
    "sinusitis": "ENT Specialist",
    "nasal blockage": "ENT Specialist",
    "nosebleeds": "ENT Specialist",
    "sore throat": "ENT Specialist",
    "tonsillitis": "ENT Specialist",
    "hoarseness": "ENT Specialist",
    "dizziness": "ENT Specialist",
    "vertigo": "ENT Specialist",

    # Eyes
    "blurred vision": "Ophthalmologist",
    "double vision": "Ophthalmologist",
    "cataract": "Ophthalmologist",
    "glaucoma": "Ophthalmologist",
    "red eyes": "Ophthalmologist",
    "dry eyes": "Ophthalmologist",
    "conjunctivitis": "Ophthalmologist",
    "eye pain": "Ophthalmologist",
    "eye strain": "Ophthalmologist",
    "vision loss": "Ophthalmologist",
    "diabetic retinopathy": "Ophthalmologist",
    "macular degeneration": "Ophthalmologist",

    # Kidneys / Urinary
    "kidney pain": "Nephrologist",
    "flank pain": "Nephrologist",
    "blood in urine": "Urologist",
    "urinary tract infection": "Urologist",
    "frequent urination": "Urologist",
    "painful urination": "Urologist",
    "kidney stones": "Urologist",
    "prostate enlargement": "Urologist",
    "erectile dysfunction": "Urologist",
    "urinary incontinence": "Urologist",

    # Women’s Health
    "pregnancy": "Gynecologist",
    "pelvic pain": "Gynecologist",
    "menstrual irregularities": "Gynecologist",
    "heavy periods": "Gynecologist",
    "painful periods": "Gynecologist",
    "menopause": "Gynecologist",
    "ovarian cyst": "Gynecologist",
    "uterine fibroids": "Gynecologist",
    "endometriosis": "Gynecologist",
    "vaginal discharge": "Gynecologist",
    "vaginal infection": "Gynecologist",
    "breast lump": "Oncologist",
    "breast pain": "Gynecologist",

    # Children
    "fever in children": "Pediatrician",
    "cough in children": "Pediatrician",
    "delayed growth": "Pediatrician",
    "speech delay": "Speech Therapist",
    "developmental delay": "Pediatric Neurologist",
    "adhd in children": "Pediatric Psychiatrist",
    "autism in children": "Pediatric Neurologist",

    # Cancer
    "cancer": "Oncologist",
    "breast cancer": "Oncologist",
    "lung cancer": "Oncologist",
    "colon cancer": "Oncologist",
    "prostate cancer": "Oncologist",
    "leukemia": "Oncologist",
    "lymphoma": "Oncologist",
    "melanoma": "Oncologist",
    "cervical cancer": "Oncologist",

    # Dental
    "toothache": "Dentist",
    "bleeding gums": "Dentist",
    "bad breath": "Dentist",
    "cavities": "Dentist",
    "sensitive teeth": "Dentist",
    "wisdom tooth": "Dentist",
    "tooth decay": "Dentist",
    "oral ulcer": "Dentist",

    # Blood / Immune
    "anemia": "Hematologist",
    "low hemoglobin": "Hematologist",
    "low platelets": "Hematologist",
    "blood clotting disorder": "Hematologist",
    "hemophilia": "Hematologist",
    "immune deficiency": "Immunologist",
    "hiv": "Infectious Disease Specialist",
    "covid": "Infectious Disease Specialist",
    "dengue": "Infectious Disease Specialist",
    "malaria": "Infectious Disease Specialist",
    "typhoid": "Infectious Disease Specialist",
}
